### PR TITLE
Remove em from line-height

### LINKED ISSUE #27: Paragraph block with large/extra-large text needs bigger line-height
I have checked Popper with the Gutenberg sample data from this post:
https://artisanthemes.io/sample-content-blocks-gutenberg/

And it needs a bigger `line-height` value for paragraphs with text set to `large` or `extra-large`

See this screenshot:
Bildschirmfoto 2020-12-27 um 21 11 43

### PR DESCRIPTION
**Pull request by Zodiac1978**
Unitless numbers in best practice for line-height values

Fixes #27

### CODE REVIEW

**Comment by bueltge** [comment]
Whether you use the em unit or a pure number is a different issue. Using just a number, as in line-height: 1.2, is primarily equivalent to using the em unit, as in line-height: 1.2em. But there is the difference that when line-height is inherited, it is the pure number that gets inherited, not the computed value. I mean if you use font-size a unit, you should also use them at the line-hight.
https://developer.mozilla.org/en-US/docs/Web/CSS/line-height

But I understand this fast solution for the issues with the css classes from Gutenberg. THe easiest and solid way to solve them.

**Comment by Zodiac1978** [comment]
> if you use font-size a unit, you should also use them at the line-hight.

I don't think you are right here. See the link you posted:
https://developer.mozilla.org/en-US/docs/Web/CSS/line-height#prefer_unitless_numbers_for_line-height_values

The example is exactly what happens in Popper.

**Comment by bueltge** [comment]
Yes, I read them and it is the fastest way to solve the problem. But is not always the best way for the 'Design'. However, I would accept them in the context that we need a solid solution because Gutenberg has to fast changes.

**Review by bueltge — APPROVED** [review]

**Comment by Zodiac1978** [comment]
I am still not sure what you want to tell me. It is the preferred way to not use units. So why not for the design? I just replaced those which used em and not any of those with pixel. Is this what you mean?

**Comment by bueltge** [comment]
No. I know that it helps to get always a readable result. But I mean that a unit on the font-size and line-hight is more for the focus to create a Design. Without a unit at the line-height, we get always the result of the browser and haven't any control over the result. Maybe more clear? But not important, your result is fine for me.

**Pull request merged**
